---

# http://docs.ansible.com/ansible/latest/apt_module.html
- name: Install the Apache mod_security2 module for Debian or Ubuntu
  apt:
    name: libapache2-mod-security2
    update_cache: yes
    state: latest
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install the Apache mod_security2 module for Red Hat or CentOS
  yum: name="{{ item }}" update_cache=yes state=latest
  with_items:
    - mod_security
    - mod_security_crs
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat' or ansible_distribution == 'Amazon'

# http://docs.ansible.com/ansible/latest/apache2_module_module.html
- name: enable mod_security2 in Debian and Ubuntu
  apache2_module:
    name: security2
    state: present
  notify:
   - restart apache2
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'


# http://docs.ansible.com/ansible/latest/template_module.html
- name: Deploy modsecurity.conf file in Debian and Ubuntu
  template:
    src: "modsecurity.conf-recommended.j2"
    dest: "{{ apache_conf_dir_debian }}/mod_security.conf"
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

# http://docs.ansible.com/ansible/latest/template_module.html
 - name: Deploy modsecurity.conf file in Red Hat
   template:
     src: "modsecurity.conf-recommended.j2"
     dest: "{{ apache_conf_dir_redhat }}/mod_security.conf"
     owner: root
     group: root
     mode: 0644
   when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat' or ansible_distribution == 'Amazon' 


# a2enconf modsecurity.conf
- name: enable mod_security2 config file in Debian and Ubuntu
  command: "a2enconf modsecurity.conf"
  notify:
  - restart apache2
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

# check if module mod_security.conf is enabled in red hat
- name: enable mod_security2 config file in Red Hat
  stat:
    path: /etc/httpd/conf.modules.d/10-mod_security.conf
  register: modsec


- name: restart apache in Red Hat if mod_security.conf is enabled just in case
  service:
    name: httpd
    state: restarted
  when: modsec.stat.exists is defined and modsec.stat.exists and (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'RedHat' or ansible_distribution == 'Amazon' )
